# You can put custom rules here
# Window/layer rules: https://wiki.hyprland.org/Configuring/Window-Rules/
# Workspace rules: https://wiki.hyprland.org/Configuring/Workspace-Rules/

windowrule = border_size 7, rounding 0, match:fullscreen 1
# Bind Claude terminal to special workspace
workspace = special:opencode, on-created-empty:kitty --directory ~/git_clones --class kitty-opencode -e zsh -i -c opencode, gapsout:30
workspace = special:browser, gapsout:30


